name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build and test
    uses: ./.github/workflows/reusable-build.yml
    with:
      configuration: Release
      publish: true
      upload_test_results: true
